// Code generated by MockGen. DO NOT EDIT.
// Source: src/boundary//area/Boundary.go

// Package area is a generated GoMock package.
package area

import (
	aggregates "deffish-server/src/aggregates"
	gomock "github.com/golang/mock/gomock"
	observable "github.com/reactivex/rxgo/observable"
	reflect "reflect"
)

// MockIRepository is a mock of IRepository interface
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// Insert mocks base method
func (m *MockIRepository) Insert(arg0 aggregates.Area) (aggregates.Id, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0)
	ret0, _ := ret[0].(aggregates.Id)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert
func (mr *MockIRepositoryMockRecorder) Insert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockIRepository)(nil).Insert), arg0)
}

// GetByName mocks base method
func (m *MockIRepository) GetByName(arg0 string) (aggregates.Area, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", arg0)
	ret0, _ := ret[0].(aggregates.Area)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName
func (mr *MockIRepositoryMockRecorder) GetByName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockIRepository)(nil).GetByName), arg0)
}

// MockIByNameUseCase is a mock of IByNameUseCase interface
type MockIByNameUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIByNameUseCaseMockRecorder
}

// MockIByNameUseCaseMockRecorder is the mock recorder for MockIByNameUseCase
type MockIByNameUseCaseMockRecorder struct {
	mock *MockIByNameUseCase
}

// NewMockIByNameUseCase creates a new mock instance
func NewMockIByNameUseCase(ctrl *gomock.Controller) *MockIByNameUseCase {
	mock := &MockIByNameUseCase{ctrl: ctrl}
	mock.recorder = &MockIByNameUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIByNameUseCase) EXPECT() *MockIByNameUseCaseMockRecorder {
	return m.recorder
}

// ByName mocks base method
func (m *MockIByNameUseCase) ByName(name string) observable.Observable {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByName", name)
	ret0, _ := ret[0].(observable.Observable)
	return ret0
}

// ByName indicates an expected call of ByName
func (mr *MockIByNameUseCaseMockRecorder) ByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByName", reflect.TypeOf((*MockIByNameUseCase)(nil).ByName), name)
}

// MockIUploadUseCase is a mock of IUploadUseCase interface
type MockIUploadUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockIUploadUseCaseMockRecorder
}

// MockIUploadUseCaseMockRecorder is the mock recorder for MockIUploadUseCase
type MockIUploadUseCaseMockRecorder struct {
	mock *MockIUploadUseCase
}

// NewMockIUploadUseCase creates a new mock instance
func NewMockIUploadUseCase(ctrl *gomock.Controller) *MockIUploadUseCase {
	mock := &MockIUploadUseCase{ctrl: ctrl}
	mock.recorder = &MockIUploadUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIUploadUseCase) EXPECT() *MockIUploadUseCaseMockRecorder {
	return m.recorder
}

// Upload mocks base method
func (m *MockIUploadUseCase) Upload(arg0 aggregates.Area) observable.Observable {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", arg0)
	ret0, _ := ret[0].(observable.Observable)
	return ret0
}

// Upload indicates an expected call of Upload
func (mr *MockIUploadUseCaseMockRecorder) Upload(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockIUploadUseCase)(nil).Upload), arg0)
}
